In [1]:
import pandas as pd

df = pd.read_csv("mental_health_ml_project_dataset.csv")

df.head()

,age,gender,sleep_hours,work_hours,physical_activity_hours,social_interaction_score,past_mental_health_history,mood_score,stress_level,text_length,depression_risk
0,56,Male,3.82,10.52,1.54,5.85,0,6.32,10.00,282,Medium
1,46,Other,7.44,8.36,5.12,4.58,0,7.98,4.51,150,Low
2,32,Male,5.40,4.90,2.82,3.48,1,4.88,4.71,450,Medium
3,25,Female,7.14,9.58,3.02,3.06,0,4.73,5.42,244,Low
4,38,Other,7.10,7.06,3.09,7.92,1,7.13,3.67,277,Low

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         1000 non-null   int64
 1   gender                      1000 non-null   object
 2   sleep_hours                 1000 non-null   float64
 3   work_hours                  1000 non-null   float64
 4   physical_activity_hours     1000 non-null   float64
 5   social_interaction_score    1000 non-null   float64
 6   past_mental_health_history  1000 non-null   int64
 7   mood_score                  1000 non-null   float64
 8   stress_level                1000 non-null   float64
 9   text_length                 1000 non-null   int64
 10  depression_risk             1000 non-null   object
dtypes: float64(6), int64(3), object(2)
memory usage: 86.1+ KB

In [3]:
df.isnull().sum()

age                           0
gender                        0
sleep_hours                   0
work_hours                    0
physical_activity_hours       0
social_interaction_score      0
past_mental_health_history    0
mood_score                    0
stress_level                  0
text_length                   0
depression_risk               0
dtype: int64

In [4]:
df.isnull().sum()

age                           0
gender                        0
sleep_hours                   0
work_hours                    0
physical_activity_hours       0
social_interaction_score      0
past_mental_health_history    0
mood_score                    0
stress_level                  0
text_length                   0
depression_risk               0
dtype: int64

In [5]:
df["depression_risk"].value_counts()

depression_risk
Low       585
Medium    381
High       34
Name: count, dtype: int64

In [6]:
X = df.drop("depression_risk", axis=1)
y = df["depression_risk"]

In [7]:
X["gender"].value_counts()

gender
Male      339
Female    333
Other     328
Name: count, dtype: int64

In [8]:
X = pd.get_dummies(X, columns=["gender"], drop_first=True)
X.head()

,age,sleep_hours,work_hours,physical_activity_hours,social_interaction_score,past_mental_health_history,mood_score,stress_level,text_length,gender_Male,gender_Other
0,56,3.82,10.52,1.54,5.85,0,6.32,10.00,282,True,False
1,46,7.44,8.36,5.12,4.58,0,7.98,4.51,150,False,True
2,32,5.40,4.90,2.82,3.48,1,4.88,4.71,450,True,False
3,25,7.14,9.58,3.02,3.06,0,4.73,5.42,244,False,False
4,38,7.10,7.06,3.09,7.92,1,7.13,3.67,277,False,True

In [9]:
X = pd.get_dummies(X, columns=["gender"], drop_first=True)
X.head()

KeyError: "None of [Index(['gender'], dtype='object')] are in the [columns]"

In [10]:
df = pd.read_csv("mental_health_ml_project_dataset.csv")

X = df.drop("depression_risk", axis=1)
y = df["depression_risk"]

X = pd.get_dummies(X, columns=["gender"], drop_first=True)

X.head()

,age,sleep_hours,work_hours,physical_activity_hours,social_interaction_score,past_mental_health_history,mood_score,stress_level,text_length,gender_Male,gender_Other
0,56,3.82,10.52,1.54,5.85,0,6.32,10.00,282,True,False
1,46,7.44,8.36,5.12,4.58,0,7.98,4.51,150,False,True
2,32,5.40,4.90,2.82,3.48,1,4.88,4.71,450,True,False
3,25,7.14,9.58,3.02,3.06,0,4.73,5.42,244,False,False
4,38,7.10,7.06,3.09,7.92,1,7.13,3.67,277,False,True

In [11]:
X.columns

Index(['age', 'sleep_hours', 'work_hours', 'physical_activity_hours',
       'social_interaction_score', 'past_mental_health_history', 'mood_score',
       'stress_level', 'text_length', 'gender_Male', 'gender_Other'],
      dtype='object')

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [13]:
y_train.value_counts()
y_test.value_counts()

depression_risk
Low       117
Medium     76
High        7
Name: count, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/home/alvi/anaconda3/envs/mh_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.945

Classification Report:

              precision    recall  f1-score   support

        High       0.86      0.86      0.86         7
         Low       0.97      0.96      0.96       117
      Medium       0.92      0.93      0.93        76

    accuracy                           0.94       200
   macro avg       0.91      0.92      0.92       200
weighted avg       0.95      0.94      0.95       200


Confusion Matrix:

[[  6   0   1]
 [  0 112   5]
 [  1   4  71]]

In [17]:
X = df.drop(["depression_risk", "stress_level"], axis=1)
y = df["depression_risk"]

X = pd.get_dummies(X, columns=["gender"], drop_first=True)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=52,
    stratify=y
)

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

/home/alvi/anaconda3/envs/mh_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [20]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.875
              precision    recall  f1-score   support

        High       0.60      0.43      0.50         7
         Low       0.90      0.95      0.92       117
      Medium       0.86      0.80      0.83        76

    accuracy                           0.88       200
   macro avg       0.78      0.73      0.75       200
weighted avg       0.87      0.88      0.87       200

In [21]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

In [22]:
model_balanced = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=52
)

In [23]:
model_balanced.fit(X_train, y_train)

y_pred_bal = model_balanced.predict(X_test)

/home/alvi/anaconda3/envs/mh_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [24]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_bal))
print(classification_report(y_test, y_pred_bal))

Accuracy: 0.87
              precision    recall  f1-score   support

        High       0.56      0.71      0.62         7
         Low       0.91      0.91      0.91       117
      Medium       0.84      0.82      0.83        76

    accuracy                           0.87       200
   macro avg       0.77      0.81      0.79       200
weighted avg       0.87      0.87      0.87       200